#!/usr/bin/env node
/**
 * Seed Setup — generates wallet seed encrypted with WDK Secret Manager.
 *
 * Usage:
 *   node scripts/seed-setup.mjs --passphrase "your-passphrase-12-chars-min"
 *   node scripts/seed-setup.mjs --passphrase "..." --name "Ludwig"
 *
 * This script:
 * 1. Takes a human-provided passphrase (12+ chars)
 * 2. Generates entropy + BIP39 mnemonic via WDK Secret Manager
 * 3. Encrypts seed + entropy with XSalsa20-Poly1305 (PBKDF2-derived key)
 * 4. Stores encrypted files on disk (.oikos-seed.enc, .oikos-salt)
 * 5. NO plaintext seed EVER touches disk
 *
 * Recovery: human remembers passphrase → decrypt on any machine.
 * At wallet boot: passphrase decrypts seed → WDK initializes.
 *
 * Uses WDK Secret Manager (sodium-native + PBKDF2-SHA256, 100k iterations).
 * Requires: node scripts/patch-wdk.js (patches bare-crypto → node:crypto)
 *
 * @security Seed material exists only in memory during generation.
 * The passphrase is the ONLY thing the human needs to remember.
 */

import { writeFileSync, readFileSync, existsSync, chmodSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

// Parse args
const args = process.argv.slice(2);
const getArg = (name) => {
  const idx = args.indexOf(name);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : null;
};

const passphrase = getArg('--passphrase');
const agentName = getArg('--name') || 'Oikos-Agent';
const envPath = getArg('--env') || resolve(projectRoot, '.env');
const encSeedPath = resolve(projectRoot, '.oikos-seed.enc');
const encEntropyPath = resolve(projectRoot, '.oikos-entropy.enc');
const saltPath = resolve(projectRoot, '.oikos-salt');

if (!passphrase || passphrase.length < 12) {
  process.stderr.write('[seed-setup] ERROR: --passphrase required (12+ characters)\n');
  process.stderr.write('[seed-setup] Usage: node scripts/seed-setup.mjs --passphrase "your-secret-phrase"\n');
  process.exit(1);
}

// Check if encrypted seed already exists
if (existsSync(encSeedPath) && existsSync(saltPath)) {
  process.stderr.write(`[seed-setup] Encrypted seed already exists at ${encSeedPath}\n`);
  process.stderr.write('[seed-setup] To regenerate, delete .oikos-seed.enc and .oikos-salt first.\n');
  process.stdout.write(JSON.stringify({ status: 'exists', encSeedPath, saltPath }) + '\n');
  process.exit(0);
}

// Ensure patch is applied
const smPath = resolve(projectRoot, 'node_modules/@tetherto/wdk-secret-manager/src/wdk-secret-manager.js');
if (existsSync(smPath)) {
  const smSource = readFileSync(smPath, 'utf8');
  if (smSource.includes("require('bare-crypto')") && !smSource.includes("require('crypto')")) {
    process.stderr.write('[seed-setup] Applying bare-crypto patch...\n');
    const { execSync } = await import('node:child_process');
    execSync(`node ${resolve(__dirname, 'patch-wdk.js')}`, { stdio: 'inherit' });
  }
}

// Import WDK Secret Manager
const { WdkSecretManager, wdkSaltGenerator } = await import('@tetherto/wdk-secret-manager');

// Generate salt
const salt = wdkSaltGenerator.generate();

// Create secret manager with passphrase
const sm = new WdkSecretManager(passphrase, salt);

// Generate entropy, encrypt seed + entropy (no plaintext touches disk)
const { encryptedSeed, encryptedEntropy } = await sm.generateAndEncrypt();

// Recover mnemonic in memory (for .env, then zeroize)
const entropy = sm.decrypt(encryptedEntropy);
const mnemonic = sm.entropyToMnemonic(entropy);

// Write encrypted files
writeFileSync(encSeedPath, encryptedSeed);
writeFileSync(encEntropyPath, encryptedEntropy);
writeFileSync(saltPath, salt);
try {
  chmodSync(encSeedPath, 0o600);
  chmodSync(encEntropyPath, 0o600);
  chmodSync(saltPath, 0o600);
} catch { /* non-critical */ }

// Write .env with the seed (wallet-isolate needs it at boot)
// Future: wallet-isolate decrypts at boot with passphrase, no plaintext .env
let envContent = '';
if (existsSync(envPath)) {
  envContent = readFileSync(envPath, 'utf-8');
  envContent = envContent.replace(
    /^WALLET_SEED="?[^"\n]*"?/m,
    `WALLET_SEED="${mnemonic}"`
  );
} else {
  envContent = `# Oikos Protocol — Generated by seed-setup.mjs
# ${new Date().toISOString()}
OIKOS_MODE="testnet"
WALLET_SEED="${mnemonic}"
WALLET_PASSPHRASE="${passphrase}"
MOCK_WALLET="false"
MOCK_SWARM="false"
SWARM_ENABLED="true"
AGENT_NAME="${agentName}"
AGENT_CAPABILITIES="payment,swap,bridge,yield,analysis,price-feed"
DASHBOARD_PORT="3420"
DASHBOARD_HOST="0.0.0.0"
WALLET_RUNTIME="node"
WALLET_ISOLATE_PATH="./wallet-isolate/dist/src/main.js"
POLICY_FILE="policies.json"
AUDIT_LOG_PATH="audit.jsonl"
ETH_RPC_URL="https://rpc.sepolia.org"
BTC_NETWORK="testnet"
`;
}

writeFileSync(envPath, envContent);
try { chmodSync(envPath, 0o600); } catch { /* non-critical */ }

// Dispose secret manager (zeroize passphrase + salt from memory)
sm.dispose();

// Output machine-readable status (NO seed material!)
const wordCount = mnemonic.split(' ').length;
process.stdout.write(JSON.stringify({
  status: 'created',
  encSeedFile: encSeedPath,
  encEntropyFile: encEntropyPath,
  saltFile: saltPath,
  envFile: envPath,
  wordCount,
  agentName,
  encryption: 'XSalsa20-Poly1305',
  kdf: 'PBKDF2-SHA256 (100k iterations)',
}) + '\n');

process.stderr.write(`[seed-setup] Seed generated (${wordCount} words) and encrypted\n`);
process.stderr.write(`[seed-setup] Encrypted seed: ${encSeedPath}\n`);
process.stderr.write(`[seed-setup] Salt: ${saltPath}\n`);
process.stderr.write(`[seed-setup] Passphrase is the ONLY way to recover this wallet.\n`);
